# assuming that you run this from a folder with sub gazpar_2_mqtt
version: '3.8'
services:
  gazpar2mqtt:
    container_name: gazpar_2_mqtt
    image: gandulf78/gazpar_2_mqtt:0.8.8
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    # network_mode can be used then you have connectivity issues, e.g. with Influx
    #network_mode: "host" 
    env_file: gazpar.env
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Paris}
    volumes:
      - ./data:/data:rw
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'python3 /app/gazpar2mqtt.py' | grep -v grep || exit 1"]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 30s
    read_only: true
    tmpfs:
      - /tmp
